### PR TITLE
Accept A JSON array

### PR DESCRIPTION
**Pull request by ghost**
[ { "message":"Message 1", "number":"1234567890", "messageId":"1" }, {	"message":"Message 2", "number":"1234567890", "messageId":"2" }, { "message":"Message 3", "number":"1234567890", "messageId":"3" } ]

### CODE REVIEW

**Comment by juancrescente** [comment]
nice! I'll give it a try.

**Comment by ampped101** [comment]
Thanks! Currently trying to figure out how to switch SIM slots.

**Comment by min0taur** [comment]
This is Great! looking forward for Dual Sim support and a built in HTTP server like REST SMS Gateway ;)

**Comment by jgui1129** [comment]
Hello @juancrescente , can we merge this feature?

**Comment by juancresc** [comment]
I haven't tested this actually but since you're asking for it I'll merge it

**Comment by jgui1129** [comment]
Thanks!

**Comment by Hidroxid** [comment]
Hello!

Any one has test SMSHub with recently Android version? I test with a Samsung A50 and dont work.

The log screen dont show anything (only ee). I send the JSON and nothing happens.

Thanks in advance.

**Pull request merged**
